/** @type {import('prettier').Config} */
module.exports = {
    endOfLine: "crlf",
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "es5",
    importOrder: [
        "^(react/(.*)$)|^(react$)",
        "^(react-native/(.*)$)|^(react-native$)",
        "^(expo/(.*)$)|^(expo$)",
        "<THIRD_PARTY_MODULES>",
        "^types$",
        "^@/types/(.*)$",
        "^@/config/(.*)$",
        "^@/lib/(.*)$",
        "^@/hooks/(.*)$",
        "^@/components/(.*)$",
        "^@/styles/(.*)$",
        "^@/app/(.*)$",
        "^[./]",
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
    importOrderGroupNamespaceSpecifiers: true,
    importOrderCaseInsensitive: true,
    importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
    plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
}